server:
  port: ":8080"
  mode: "development"

database:
  host: "localhost" 
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "market_db"

jwt:
  secret: "your-secret-key"
  expiry_hours: 24

cors:
  allowed_origins:
    - "http://localhost:3000"